// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __RAIL_CONFIG__
#define __RAIL_CONFIG__




// Top level macros
#define RAIL_DEVICE_NAME "railtest_efr32"


// Generated plugin macros

// Use this macro to check if Buffer pool memory manager plugin is included
#define RAIL_PLUGIN_BUFFER_POOL_MEMORY_MANAGER
// User options for plugin Buffer pool memory manager
#define BUFFER_POOL_SIZE 10
#define MAX_BUFFER_SIZE 256

// Use this macro to check if Circular queue plugin is included
#define RAIL_PLUGIN_CIRCULAR_QUEUE
// User options for plugin Circular queue
#define MAX_QUEUE_LENGTH 10

// Use this macro to check if Command Interpreter for RAIL plugin is included
#define RAIL_PLUGIN_COMMAND_INTERPRETER
// User options for plugin Command Interpreter for RAIL
#define MAX_COMMAND_ARGUMENTS 20

// Use this macro to check if HAL library for RAIL plugin is included
#define RAIL_PLUGIN_HAL_EFR32

// Use this macro to check if Application Graphics for RAIL plugin is included
#define RAIL_PLUGIN_LCD_GRAPHICS

// Use this macro to check if RAIL Library plugin is included
#define RAIL_PLUGIN_RAIL_LIB

// Use this macro to check if railtest Application plugin is included
#define RAIL_PLUGIN_RAILTEST_BASE
// User options for plugin railtest Application
#define APP_DEMO_STRING_INIT "RAIL Test App"
#define APP_DEMO_STRING_INIT_LENGTH (13)
#define APP_DISPLAY_BUFFER_SIZE 64
#define APP_MAX_PACKET_LENGTH 240
#define APP_CONTINUOUS_TRANSFER_PERIOD 250
#define APP_COMMAND_INTERFACE_BUFFER_SIZE 256
#define BUTTON_HOLD_MS 1000

// Use this macro to check if Response Printf plugin is included
#define RAIL_PLUGIN_RESPONSE_PRINTF
// User options for plugin Response Printf
#define MAX_FORMAT_STRING_SIZE 256


// Generated API headers


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32FG1P133F256GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY F

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 1

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 133

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 256K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32FG1P133F256GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY F

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 1

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 133

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 256K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4250A



#endif // __RAIL_CONFIG__
