// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This callback file is created for your convenience. You may add application
// code to this file. If you regenerate this file over a previous version, the
// previous version will be overwritten and any code you have added will be
// lost.
#include <stdint.h>
#include "rail.h"
#include "rail_types.h"
#include "rail_ieee802154.h"
#include CONFIGURATION_HEADER




