// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include <stdint.h>
#include "rail.h"
#include "rail_types.h"
#include "rail_ieee802154.h"
#include CONFIGURATION_HEADER


// Templates from the callbacks info files
